# Generated by Django 3.1.3 on 2020-11-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='admin',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='staff',
            new_name='is_superuser',
        ),
    ]
